### PR TITLE
Vms x86

### PR DESCRIPTION
**Pull request by whcox603**
I did this port of the library to vms_x86 about 6 months ago. Not many changes. I did rewrite the vms_build procedure. I held off requesting a merge to await a fix for the 3 failing tests. I commented in a group somewhere and got a reply from a developer that sounded like it would be fixed in the next release, but I was not able to confirm the fix. I also noted that the one new test failure was due to C and C++ disagreeing on sizes.

My VMS_x86 license expired a month ago and I am still awaiting a new license.

Feel free to reject this if you have already done the port.

bill

### CODE REVIEW

**Comment by saprykin** [comment]
Hi Bill,

Thanks for PR. I'm actually working on VMS x86 port in the last days :) Looking into the long size issue right now, the rest was quite trivial. I did not do much changes in build_vms.com, though, maybe a few lines. I suggest that I merge my changes into your PR, as most of them are common. I have only access to Alpha and x86 in emulators, cannot test on IA64.

Did IEEE floating denormalisation cause any issues on x86?

**Comment by whcox603** [comment]
Alexander,

The only test issues I had were the 3 that were already failing, plus the one caused by the size mismatch.

**Comment by whcox603** [comment]
Do the 3 tests still fail on vms?

bill

**Comment by saprykin** [comment]
> Do the 3 tests still fail on vms?

Yes. The only difference is that semaphore test passes one time when compiled with 32-bit pointers. Each next time it fails.

**Pull request merged**
